name       : krfb
version    : 23.04.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/krfb-23.04.0.tar.xz : 321fa19779f4bc0ec6b3c2c79c9118cdaaa1376ba56d93cde4a5ef4aae27b0b6
license    :
    - AGPL-1.0-or-later
    - BSD-3-Clause
    - DOC
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Krfb Desktop Sharing is a server application that allows you to share your current session with a user on another machine, who can use a VNC client to view or even control the desktop.
description: |
    Krfb Desktop Sharing is a server application that allows you to share your current session with a user on another machine, who can use a VNC client to view or even control the desktop.
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(epoxy)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libvncserver)
    - pkgconfig(xcb-image)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
    - kcrash-devel
    - kcompletion-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kdnssd-devel
    - ki18n-devel
    - kpipewire-devel
    - knotifications-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
