name       : krfb
version    : 22.04.2
release    : 1
source     :
    - https://download.kde.org/stable/release-service/22.04.2/src/krfb-22.04.2.tar.xz : 37a4d8c0176011e74790334cdb6db548f1cc008ad83d9c33fda0df4cbbf8f98c
license    :
    - AGPL-1.0-or-later
    - BSD-3-Clause
    - DOC
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Krfb Desktop Sharing is a server application that allows you to share your current session with a user on another machine, who can use a VNC client to view or even control the desktop.
description: |
    Krfb Desktop Sharing is a server application that allows you to share your current session with a user on another machine, who can use a VNC client to view or even control the desktop.
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(epoxy)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libvncserver)
    - pkgconfig(xcb-image)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
    - kcrash-devel
    - kcompletion-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kdnssd-devel
    - ki18n-devel
    - knotifications-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
