name       : krfb
version    : 22.04.3
release    : 2
source     :
    - https://download.kde.org/stable/release-service/22.04.3/src/krfb-22.04.3.tar.xz : c13e0e2ee052be97cd6c7be4ca9533e410118292b69a2bdcbfc9ed78a82a0026
license    :
    - AGPL-1.0-or-later
    - BSD-3-Clause
    - DOC
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Krfb Desktop Sharing is a server application that allows you to share your current session with a user on another machine, who can use a VNC client to view or even control the desktop.
description: |
    Krfb Desktop Sharing is a server application that allows you to share your current session with a user on another machine, who can use a VNC client to view or even control the desktop.
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(epoxy)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libvncserver)
    - pkgconfig(xcb-image)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
    - kcrash-devel
    - kcompletion-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kdnssd-devel
    - ki18n-devel
    - knotifications-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
